### ISSUE TITLE
无法解析配置文件

### ISSUE THREAD

**Issue by saber20200** [samyycX/CS2-PlayerModelChanger#9]
插件在运行的时候会报错，
16:34:15 [INFO] (cssharp:PluginContext) Loading plugin PlayerModelChanger
16:34:15 [EROR] (cssharp:ConfigManager) Failed to parse configuration file for PlayerModelChanger
System.Text.Json.JsonException: The JSON value could not be converted to Service.Model. Path: $.Models.MenuType | LineNumber: 5 | BytePositionInLine: 20.
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonDictionaryConverter`3.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TDictionary& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at CounterStrikeSharp.API.Modules.Config.ConfigManager.Load[T](String pluginName) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Config/ConfigManager.cs:line 86
Player Model Changer loaded 0 model(s) successfully.
16:34:15 [INFO] (cssharp:PluginContext) Finished loading plugin Player Model Changer
![111](https://github.com/samyycX/CS2-PlayerModelChanger/assets/76509197/165cab5e-cb1c-47ea-be70-fc85fa26e7f5)

json文件是这样的，是我的配置文件的格式有问题吗？

**Comment by samyycX** [comment]
第四行后面少了一个`｝`

**Comment by saber20200** [comment]
> 第四行后面少了一个`｝`

好的，谢谢
